[package]
name = "donder-desktop"
edition.workspace = true
version.workspace = true
description = "Donder desktop"
authors = ["Donder"]
license = "MIT"
default-run = "donder-desktop"

[dependencies]
camino.workspace = true
bytemuck.workspace = true
donder-project-io.workspace = true
donder-language-server.workspace = true
lsp-types.workspace = true
donder-sequence-api.workspace = true
donder-editor.workspace = true
sha2.workspace = true
donder-language.workspace = true
donder-model.workspace = true
donder-runtime-types.workspace = true
donder-output.workspace = true
donder-audio-analysis.workspace = true
fdk-aac.workspace = true
openh264.workspace = true
shiguredo_mp4.workspace = true
donder-elaboration.workspace = true
donder-runtime.workspace = true
glam.workspace = true
ignore.workspace = true
notify.workspace = true
indexmap.workspace = true
kira.workspace = true
reqwest.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
serialport.workspace = true
espflash.workspace = true
mdns-sd.workspace = true
esp-idf-part.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tauri.workspace = true
tauri-specta.workspace = true
wgpu.workspace = true
winit.workspace = true
uuid.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "donder-desktop"
path = "src/main.rs"
